blank_issues_enabled: true
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/YOUR_USERNAME/vibeleaks/discussions
    about: Ask questions and discuss ideas with the community
  - name: 📖 Documentation
    url: https://vibeleaks.lovable.app
    about: Read the project documentation and usage guides
  - name: 🔒 Security Issue
    url: https://github.com/YOUR_USERNAME/vibeleaks/security/advisories/new
    about: Report a security vulnerability (private disclosure)
